### ISSUE TITLE
Single SMS to multiple destination is broken

### ISSUE THREAD

**Issue by maotora** [nextsms/node-nextsms#39]
Hello,

awesome library, I made this issue as a good Ref. that single SMS to multiple destination implementation is kinda off.
I observed this is the modules directory & interfaces and found out that it is using multiple messages to multiple destination interface which is not quite made for it and also the route it is submitting too is not the right one as per Next SMS docs.

<img width="595" alt="Screenshot 2023-07-11 at 16 51 23" src="https://github.com/nextsms/node-nextsms/assets/5174884/e43f5ea2-397a-4373-8244-714a3449937b">

**Comment by alphaolomi** [comment]
Thank you @maotora for raising this issue.

**Comment by maotora** [comment]
@alphaolomi no problem, I would advise on updating the npm registry as well, it appears to be deprecated over there and it has not been updated to the new version 1.1.0

Please ping me when the update is done so I can update my dependencies as well, as of now I'm using the github repository package instead of npm one.
